### ISSUE TITLE
yum: dvc package version 2.35.1-1 is missing libcrypt.so.2

### ISSUE THREAD

**Issue by aschuh-hf** [iterative/dvc-s3-repo#89]
# Bug Report

## Description

I've just updated to the latest version using `yum update dvc` from 2.31.0 to 2.35.1. After the update, `dvc` is broken because it cannot find `libcrypt.so.2`.

```
Error loading Python lib '/usr/lib/dvc/libpython3.10.so.1.0': dlopen: libcrypt.so.2: cannot open shared object file: No such file or directory
```

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
```

Docker container based on CentOS 7.8.2003

**Additional Information (if any):**

**Comment by efiop** [comment]
Looks like we need to declare it as a dependency, as bundling it doesn't seem great https://github.com/pyinstaller/pyinstaller/issues/6618

@aschuh-hf Could you try installing libcrypt and see if that fixes it for you?

**Comment by efiop** [comment]
Also note that centos 7 is old and reached EOL and not supported anymore. We migrated to using fedora 35 for building our rpm package (because even building python 3.10 on centos 7 and installing deps was now problematic), which means that you might run into other libraries being incompatible (e.g. our rpm requiring a newer libc than the one that you have).

**Comment by aschuh-hf** [comment]
Thanks for the quick reply! I've tried `yum install libcrypt`, but get the message `No package libcrypt available.`. Wasn't able yet to figure out from which source I can install this library. I'm on CentOS 7.

**Comment by aschuh-hf** [comment]
> Also note that centos 7 is old and reached EOL and not supported anymore. We migrated to using fedora 35 for building our rpm package (because even building python 3.10 on centos 7 and installing deps was now problematic), which means that you might run into other libraries being incompatible (e.g. our rpm requiring a newer libc than the one that you have).

Hm. I will have to speak to our IT support who would decide on whether we can upgrade, which for various reasons isn't that trivial. Other internal tools are still build for CentOS 7.

**Comment by aschuh-hf** [comment]
Would installation using `conda install -c conda-forge dvc dvc-s3` still be an option on CentOS 7 for the latest versions?

**Comment by efiop** [comment]
Oh, correction, centos did not reach EOL yet, that's my mistake.

**Comment by efiop** [comment]
Yes, conda should still work.

Could you try installing libcrypt package or do you not have control over system packages?

**Comment by aschuh-hf** [comment]
I'm inside a Docker container and could install `libcrypt`. However, `yum install libcrypt` does not find it?

The latest dvc version seems to be not available as conda package just yet. The latest at the moment is 2.34.2.

I've tried `pipx install dvc[s3]`, but am having issues with this as well:
```
Fatal error from pip prevented installation. Full pip output in file:
    /opt/pipx/logs/cmd_2022-11-24_10.52.12_pip_errors.log

pip failed to build package:
    pygit2

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    src/diff.h:33:10: fatal error: git2.h: No such file or directory
    error: command '/bin/gcc' failed with exit code 1
```

**Comment by aschuh-hf** [comment]
FYI: I'm mainly trying to update now to the latest version to see if it resolves [this issue](https://github.com/iterative/dvc/issues/8613).

**Comment by efiop** [comment]
Hm, looks like libcrypt is deprecated and maybe this one could be fixed on our side while building the package. I'll take look now.

**Comment by aschuh-hf** [comment]
That would be great. Thanks for looking into it!

**Comment by efiop** [comment]
@aschuh-hf Looks like I got double confused. It is libcrypt.so.2 and not libcrypt.so.1, so it is not obsoleted, but provided by a different package. I'm not sure if centos 7 has it, but could you try installing libxcrypt (notice the x), please?

Overall it looks like the problem I've described above, where we build using a newer distro with newer libraries that are missing in older distros (usually it is glibc, but in this case it is a former glibc library - libcrypt). Even if you install libxcrypt, it is very likely that you'll run into other similar issues. Though upgrading to centos 8 (or centos stream 8 or 9, since centos 8 is dead) should be a proper way forward.

Regarding conda, the package will be available later today (it is not triggered by us, so we don't have control over it).

Closing this issue since we can't go back to building on centos 7.

**Comment by aschuh-hf** [comment]
> I'm not sure if centos 7 has it, but could you try installing libxcrypt (notice the x), please?

I've tried `libxcrypt` as well after a quick internet search, but it wasn't found either.

> Regarding conda, the package will be available later today

Great, that should do as well. In the meantime, I noticed that the issues I had with `pip install` are due to `pygit2`. After installing `pygit2` with `conda`, I was able to install the latest DVC version from PyPI using `pip`.

> Closing this issue since we can't go back to building on centos 7.

Fair enough. I will update our Docker build files to use the conda package instead of the RPM.

Thanks for taking the time!
